[build]
  command = "yarn build"
  publish = "out"

[[redirects]]
  from = "https://www.kevinporten.de/*"
  to = "https://www.kevinporten.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://kevinporten.de/*"
  to = "https://www.kevinporten.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.kevin-porten.de/*"
  to = "https://www.kevinporten.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://kevin-porten.de/*"
  to = "https://www.kevinporten.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://kevinporten.netlify.com/*"
  to = "https://www.kevinporten.dev/:splat"
  status = 301
  force = true
