name: production

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run integration tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
          start: yarn dev
          wait-on: http://localhost:3000
      - name: Run component tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn test --record false
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          args: --severity-threshold=high --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  deploy:
    needs: [test, security]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --message $GITHUB_REF
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
